### ISSUE TITLE
Query service (such as openstreemap's lookup services) that can take a city / town and return it's co-ordinates.

### ISSUE THREAD

**Issue by mfw78** [windingtree/win-stays#115]
**Problem**

When wanting to search for a city, we need a way of changing this to a latitude and longitude, and refocusing the map.

**Solution**

Using [Nominatim](https://wiki.openstreetmap.org/wiki/Nominatim) and their geocoding service, take in user input, query the API, then refocus the map.

**Comment by lucarioams** [comment]
@bobetbat does this have any impact on how we should design the UX/UI flow on the front-end?
