### ISSUE TITLE
story: data model for storage and search message

### ISSUE THREAD

**Issue by lucarioams** [windingtree/win-stays#33]
**🚨 WARNING: THIS IS A BLOCKING ISSUE 🚨**

**Problem**

Need to define the data model for:

- [x] Storage of metadata accessed by end users (`stays`)

  - [x] Image storage (assumed that images would be lazy-loaded)

- [x] Search message sent via on `videre` which constitutes the base requirements.

**Comment by mfw78** [comment]
This issue does **NOT** deal with the _location_ of storage, but only relates to models / schemas.
