### ISSUE TITLE
feat(stays-models): contact information for accommodation providers

### ISSUE THREAD

**Issue by mfw78** [windingtree/win-stays#71]
**Problem**

Need some method of conveying contact information for the accommodation provider

**Solution**

Add contact information to the storage protobuf. **Need to determine schema for this**

**Comment by lucarioams** [comment]
```protobuf

message PR_Name { 

message PR_Email {

message PR_Telephone {
// country code

message PR_website {

```

also created those for the guest information ⬇ 
[Data Schemas ETHBCN x ETHcc](https://www.notion.so/windingtree/Data-Schemas-ETHBCN-x-ETHcc-c51720a9bc2f405c80a0daf749538e1f)
